/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutBackupsRouteImport } from './routes/_layout.backups'
import { Route as LayoutDownloadsRouteImport } from './routes/_layout.downloads'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBackupsRoute = LayoutBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDownloadsRoute = LayoutDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/backups': typeof LayoutBackupsRoute
  '/downloads': typeof LayoutDownloadsRoute
}
export interface FileRoutesByTo {
  '/backups': typeof LayoutBackupsRoute
  '/downloads': typeof LayoutDownloadsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/backups': typeof LayoutBackupsRoute
  '/_layout/downloads': typeof LayoutDownloadsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backups' | '/downloads'
  fileRoutesByTo: FileRoutesByTo
  to: '/backups' | '/downloads' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/backups'
    | '/_layout/downloads'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/backups': {
      id: '/_layout/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof LayoutBackupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/downloads': {
      id: '/_layout/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LayoutDownloadsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutBackupsRoute: typeof LayoutBackupsRoute
  LayoutDownloadsRoute: typeof LayoutDownloadsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBackupsRoute: LayoutBackupsRoute,
  LayoutDownloadsRoute: LayoutDownloadsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
